import '@styles/globals.css'
import Nav from '@components/Nav';

export const metadata = {
  title: 'Jasper Ayawan - Software Engineer',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main className='app'>
          <Nav />
          {children}
        </main>
      </body>
    </html>
  )
}
